import {
  Dialog, DialogTitle, DialogContent, DialogActions,
  Button, Typography, Box, IconButton, Divider, useTheme,
} from "@mui/material";

const CloseIcon = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
  </svg>
);

type LegalType = "terms" | "privacy";

interface Props {
  open:    boolean;
  type:    LegalType;
  onClose: () => void;
}

const TERMS_SECTIONS = [
  {
    heading: "1. Acceptance of Terms",
    body:    "By accessing or using RouteGenie, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the service.",
  },
  {
    heading: "2. Description of Service",
    body:    "RouteGenie is an AI-powered travel planning platform that helps users create personalised itineraries, track bookings, and access live travel data. The service is provided as-is for personal, non-commercial use.",
  },
  {
    heading: "3. User Accounts",
    body:    "You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must provide accurate and complete information when creating an account.",
  },
  {
    heading: "4. Acceptable Use",
    body:    "You agree not to misuse the service, attempt to gain unauthorised access to any part of the platform, transmit harmful or illegal content, or use automated tools to scrape or abuse the service.",
  },
  {
    heading: "5. AI-Generated Content",
    body:    "Itineraries and recommendations generated by our AI are for informational purposes only. RouteGenie does not guarantee the accuracy, completeness, or suitability of AI-generated travel plans. Always verify critical travel information independently.",
  },
  {
    heading: "6. Limitation of Liability",
    body:    "To the maximum extent permitted by law, RouteGenie shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.",
  },
  {
    heading: "7. Changes to Terms",
    body:    "We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes your acceptance of the updated terms.",
  },
];

const PRIVACY_SECTIONS = [
  {
    heading: "1. Information We Collect",
    body:    "We collect information you provide directly (name, email, date of birth, travel preferences) and usage data (pages visited, features used, device type) to improve our service.",
  },
  {
    heading: "2. How We Use Your Information",
    body:    "Your information is used to provide and personalise the RouteGenie service, generate AI itineraries tailored to your preferences, send account-related notifications, and improve our platform.",
  },
  {
    heading: "3. Data Storage & Security",
    body:    "Your data is stored securely on MongoDB Atlas with encryption at rest. Authentication tokens are managed with industry-standard JWT with short expiry windows and Redis-based invalidation.",
  },
  {
    heading: "4. Third-Party Services",
    body:    "RouteGenie integrates with third-party APIs (weather, exchange rates, destination photos) to provide live travel data. These providers have their own privacy policies which govern data shared with them.",
  },
  {
    heading: "5. Data Retention",
    body:    "We retain your account data for as long as your account is active. You may request deletion of your account and associated data at any time by contacting us.",
  },
  {
    heading: "6. Cookies & Local Storage",
    body:    "We use browser local storage to persist your session and UI preferences (such as dark/light mode). We do not use third-party tracking cookies.",
  },
  {
    heading: "7. Your Rights",
    body:    "You have the right to access, correct, or delete your personal data. To exercise these rights or with any privacy questions, please reach out through the contact information on our website.",
  },
];

const CONTENT = {
  terms:   { title: "Terms of Service",  lastUpdated: "January 2025", sections: TERMS_SECTIONS   },
  privacy: { title: "Privacy Policy",    lastUpdated: "January 2025", sections: PRIVACY_SECTIONS },
};

export function LegalModal({ open, type, onClose }: Props) {
  const theme  = useTheme();
  const isDark = theme.palette.mode === "dark";
  const { title, lastUpdated, sections } = CONTENT[type];

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="sm"
      fullWidth
      scroll="paper"
      slotProps={{
        paper: {
          sx: {
            backgroundColor: isDark ? "#1A150D" : "#FDFAF5",
            border:          `1px solid ${isDark ? "rgba(245,158,11,0.12)" : "rgba(0,0,0,0.08)"}`,
            borderRadius:    "16px",
            backgroundImage: "none",
          },
        },
      }}
    >
      {/* Header */}
      <DialogTitle sx={{ p: "20px 24px 16px", display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 1 }}>
        <Box>
          <Box sx={{ display: "flex", alignItems: "center", gap: 1.25, mb: 0.5 }}>
            <Box component="img" src="/Icon.png" alt="RouteGenie" sx={{ height: 22, width: "auto" }} />
            <Typography sx={{ color: theme.palette.primary.main, fontFamily: '"DM Serif Display", serif', fontSize: "0.85rem" }}>
              RouteGenie
            </Typography>
          </Box>
          <Typography sx={{ fontFamily: '"DM Serif Display", serif', color: theme.palette.text.primary, fontSize: "1.35rem", lineHeight: 1.2 }}>
            {title}
          </Typography>
          <Typography sx={{ color: theme.palette.text.secondary, fontSize: "0.72rem", mt: 0.5 }}>
            Last updated: {lastUpdated}
          </Typography>
        </Box>
        <IconButton
          onClick={onClose}
          size="small"
          sx={{
            color:           theme.palette.text.secondary,
            mt:              0.25,
            flexShrink:      0,
            "&:hover": { color: theme.palette.primary.main },
          }}
        >
          <CloseIcon />
        </IconButton>
      </DialogTitle>

      <Divider sx={{ borderColor: isDark ? "rgba(255,255,255,0.06)" : "rgba(0,0,0,0.07)" }} />

      {/* Content */}
      <DialogContent sx={{ px: "24px", py: "20px" }}>
        <Box sx={{ display: "flex", flexDirection: "column", gap: 2.5 }}>
          {sections.map((s) => (
            <Box key={s.heading}>
              <Typography sx={{ color: theme.palette.text.primary, fontWeight: 600, fontSize: "0.85rem", fontFamily: "Plus Jakarta Sans, sans-serif", mb: 0.75 }}>
                {s.heading}
              </Typography>
              <Typography sx={{ color: theme.palette.text.secondary, fontSize: "0.83rem", fontFamily: "Plus Jakarta Sans, sans-serif", lineHeight: 1.75 }}>
                {s.body}
              </Typography>
            </Box>
          ))}
        </Box>
      </DialogContent>

      <Divider sx={{ borderColor: isDark ? "rgba(255,255,255,0.06)" : "rgba(0,0,0,0.07)" }} />

      <DialogActions sx={{ px: "24px", py: "16px" }}>
        <Button onClick={onClose} variant="contained" color="primary" sx={{ px: 3, py: 0.9, fontSize: "0.85rem" }}>
          I understand
        </Button>
      </DialogActions>
    </Dialog>
  );
}
